name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Setup Racket environment
      uses: Bogdanp/setup-racket@v0.1
    - name: test racket install
      run: |
        racket -e '(printf "wow Racket! ${{secrets.cool_token}}\n")'

